[[headers]]
  for = "/journey/*.jpg"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
	Cache-Control = "public max-age=604800"

[[headers]]
  for = "/g/*.svg"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
	Cache-Control = "public max-age=604800"
