[[headers]]
  for = "*.jpg,*.png,*.svg"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

    #  Multi-value headers are expressed with multi-line strings
	cache-control = '''
	immutable,
	public'''